apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load
  name: load-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: load
    spec:
      containers:
      - image: czdev/blue
        name: load
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-client
  name: redis-client-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-client
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: redis-client
    spec:
      containers:
      - image: czdev/green
        name: redis-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-client
  name: go-client-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-client
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: go-client
    spec:
      containers:
      - image: czdev/blue
        name: go-client
---