apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-client
    client: redis
  name: redis-client-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-client
      client: redis
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: load-client
        client: redis
    spec:
      containers:
      - image: czdev/green
        name: redis-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-client
    client: go
  name: go-client-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-client
      client: go
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: load-client
        client: go
    spec:
      containers:
      - image: czdev/blue
        name: go-client
---