apiVersion: v1
kind: Service
metadata:
  labels:
    app: load
  name: load-service
  namespace: project
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: load
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-client
  name: redis-client-service
  namespace: project
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: redis-client
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-client
  name: go-client-service
  namespace: project
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: go-client